### ISSUE TITLE
Asking for username and password - Tool-X

### ISSUE THREAD

**Issue by TanZeus** [rajkumardusad/Tool-X#124]
Hey! 
Tool-x is asking for git username and password to continue what should i type in?

**Comment by rajkumardusad** [comment]
Hey @TanZeus clone proper url it will never ask username and password..
`$ git clone https://github.com/rajkumardusad/Tool-X.git`
it will works.

**Comment by TanZeus** [comment]
The tool x has been cloned tool no. 64(InstaHack) asks for username and password...

**Comment by rajkumardusad** [comment]
Ok we will fix it soon.

**Comment by TanZeus** [comment]
Man u just deleted the tool😔

**Comment by rajkumardusad** [comment]
> Man u just deleted the tool

No we have not deleted any tool?

**Comment by jdvsv** [comment]
> Hey @TanZeus clone proper url it will never ask username and password..
> `$ git clone https://github.com/rajkumardusad/Tool-X.git`
> it will works.

Same problem

**Comment by miiiiiYT** [comment]
I think there is a general problem in the understanding of Git, not in Tool-X.

To clone a repo from the command line, you need to configure Git with your username and E-Mail adress. If you're using Git on Windows, - probably not, if you're opening an issue here - then your password will automatically be saved. On any Linux device, including Android phones, there is no mechanism for saving a password. Your only other option really is using SSH instead of HTTPS. There isn't really something the dev could fix here.

**Comment by bjornanderson1** [comment]
> Hey @TanZeus clone proper url it will never ask username and password.. `$ git clone https://github.com/rajkumardusad/Tool-X.git` it will works.

hi, I am encountering to the same problem with the username and password. I followed all necessary command line and I used the last syntax for the 
git clone https://raj](https://github.com/rajkumardusad/Tool-X.git 
In some packages are required to use some username and password. I think that this issue is not yet 100% solved.

**Comment by ffffaaasl** [comment]
Hey @TanZeus clone proper url it will never ask username and password.. $ git clone https://github.com/rajkumardusad/Tool-X.git it will works.
hi, I am encountering to the same problem with the username and password. I followed all necessary command line and I used the last syntax for the
git clone https://github.com/rajkumardusad/Tool-X.git
In some packages are required to use some username and password. I think that this issue is not yet 100% solved.
