### ISSUE TITLE
i have python 2.7 and 3.8.  Still no work

### ISSUE THREAD

**Issue by battouusai** [rajkumardusad/Tool-X#153]
try following commands : 
`$ apt install python`
`$ apt install python3`
`$ pip install requests`
`$ pip3 install requests`
I hope it will work for you?

_Originally posted by @rajkumardusad in https://github.com/rajkumardusad/Tool-X/issues/134#issuecomment-652735479_

**Comment by Mohitkumar6122** [comment]
1. First make a python code and save it as **ANYNAME.py** .
2. Then **navigate the terminal to the directory where the script is located** (Using the cd command ).
3. Type **python3 ANYNAME.py** in the terminal to execute the script. (if you want to use python2 then type python instead of 
    python3 )
It will definitely work for you if python is installed on your device. 
--------------------------------------------------------------------------------------------

**Comment by battouusai** [comment]
Thanks it works now
