### ISSUE TITLE
[ + ]  No network connection?   [ + ]  Are you offline?   [ + ]  Please try again after some time.

### ISSUE THREAD

**Issue by ASHISH1722** [rajkumardusad/Tool-X#167]
how can i fix it

**Comment by Saad5588** [comment]
no thanks

**Comment by rajkumardusad** [comment]
Hey @ASHISH1722 try following commands :
$ apt install python
$ apt install python3
$ pip install requests
$ pip3 install requests
I hope it will work for you?

**Comment by miiiiiYT** [comment]
> Hey @ASHISH1722 try following commands :
> $ apt install python
> $ apt install python3
> $ pip install requests
> $ pip3 install requests
> I hope it will work for you?

That should be done automatically, but you can do it of course.

@ASHISH1722 
Please provide more info such as log files etc.

**Comment by honzo666-c** [comment]
Hey no way, you must be from gethub. I haven't been on my email for a while
but I was trying to get it running without installing all the pkg files. I
follow a couple of people on get hub and I am aware that Linux have a lot
of people developing these tools.


But hey I'm gonna try to install ToolX again because I reset The Linux app
I had so yeah I will talk to you if I have any problem again.
