### ISSUE TITLE
Cant access at all 

### ISSUE THREAD

**Issue by PrinceKK300188** [rajkumardusad/Tool-X#216]
Why it keep saying no network connection??

**Comment by sduwfc** [comment]
metoo

**Comment by zizusha** [comment]
Me 3

**Comment by miiiiiYT** [comment]
@rajkumardusad Look, there is another issue that would be fixed if you'd merge #214

**Comment by miiiiiYT** [comment]
@PrinceKK300188 It keeps saying "Not network connection", because before it even runs, it checks if you have one. The problem is, that it 90 percent of the time it falsely reports "no network connection", so the while program just quits. @rajkumardusad doesn't want to merge my PR #214, so maybe, I'll fork this repo and you can use that.

**Comment by rajkumardusad** [comment]
> @PrinceKK300188 It keeps saying "Not network connection", because before it even runs, it checks if you have one. The problem is, that it 90 percent of the time it falsely reports "no network connection", so the while program just quits. @rajkumardusad doesn't want to merge my PR #214, so maybe, I'll fork this repo and you can use that.

Ok we will look it.

**Comment by rajkumardusad** [comment]
Hey @miiiiiYT please submit new PR

**Comment by miiiiiYT** [comment]
@rajkumardusad I reopened it

**Comment by miiiiiYT** [comment]
have a look at #219

**Comment by rajkumardusad** [comment]
> have a look at #219

Ok thank you.
