### ISSUE TITLE
Not Installing Tools

### ISSUE THREAD

**Issue by aidenrossi** [rajkumardusad/Tool-X#79]
When I try to make it install a tool it says that the tool cannot be installed

**Comment by rajkumardusad** [comment]
Hey @aidenrossi we will fix it soon. you can try a new tool onex that is better then tool-x.
Onex : https://github.com/rajkumardusad/onex

**Comment by Fayad-hub** [comment]
Onex is not workingi how to id root my termux & sudo

**Comment by rajkumardusad** [comment]
Hey @Fayad-hub what is the error in onex?

**Comment by Fayad-hub** [comment]
How to id root my termuxare you help me?

**Comment by great-rex** [comment]
On Apr 2, 2020 2:55 AM, "aidenrossi" <notifications@github.com> wrote:

When I try to make it install a tool it says that the tool cannot be
installed

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rajkumardusad/Tool-X/issues/79>, or unsubscribe

**Comment by rajkumardusad** [comment]
Hey @great-rex we will fix it soon. you can try a new tool onex that is better then tool-x.
Onex : https://github.com/rajkumardusad/onex
